//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUIDemo.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EasyUIDemoDBEntities : DbContext
    {
        public EasyUIDemoDBEntities()
            : base("name=EasyUIDemoDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Action> T_SYS_Action { get; set; }
        public DbSet<Menu> T_SYS_Menu { get; set; }
        public DbSet<Module> T_SYS_Module { get; set; }
        public DbSet<Permission> T_SYS_Permission { get; set; }
        public DbSet<Role> T_SYS_Role { get; set; }
        public DbSet<User> T_SYS_User { get; set; }
        public DbSet<UserRoleRelation> T_SYS_UserRoleRelation { get; set; }
        public DbSet<tblCarNO> tblCarNO { get; set; }
        public DbSet<tblCarNO_bak> tblCarNO_bak { get; set; }
        public DbSet<UserInfo> UserInfo { get; set; }
    }
}
