//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyUIDemo.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.T_SYS_UserRoleRelation = new HashSet<UserRoleRelation>();
        }
    
        public System.Guid ID { get; set; }
        public string CnName { get; set; }
        public string EnName { get; set; }
        public string Account { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Available { get; set; }
        public Nullable<int> LoginFailCount { get; set; }
        public Nullable<System.DateTime> LastLoginFailDate { get; set; }
        public Nullable<int> UserType { get; set; }
        public string Email { get; set; }
        public string Tel { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> GenderID { get; set; }
        public string Creator { get; set; }
        public Nullable<System.DateTime> CreateTime { get; set; }
        public string LastModifier { get; set; }
        public Nullable<System.DateTime> LastModifyTime { get; set; }
    
        public virtual ICollection<UserRoleRelation> T_SYS_UserRoleRelation { get; set; }
    }
}
